/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StartRouteImport } from './routes/start'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PosterThanksRouteImport } from './routes/poster-thanks'
import { Route as PosterRouteImport } from './routes/poster'
import { Route as PeptidesRouteImport } from './routes/peptides'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoThanksDadRouteImport } from './routes/go/thanks-dad'
import { Route as GoDadsRouteImport } from './routes/go/dads'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterThanksRoute = PosterThanksRouteImport.update({
  id: '/poster-thanks',
  path: '/poster-thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterRoute = PosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const PeptidesRoute = PeptidesRouteImport.update({
  id: '/peptides',
  path: '/peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoThanksDadRoute = GoThanksDadRouteImport.update({
  id: '/go/thanks-dad',
  path: '/go/thanks-dad',
  getParentRoute: () => rootRouteImport,
} as any)
const GoDadsRoute = GoDadsRouteImport.update({
  id: '/go/dads',
  path: '/go/dads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/peptides': typeof PeptidesRoute
  '/poster': typeof PosterRoute
  '/poster-thanks': typeof PosterThanksRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/go/dads': typeof GoDadsRoute
  '/go/thanks-dad': typeof GoThanksDadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/peptides': typeof PeptidesRoute
  '/poster': typeof PosterRoute
  '/poster-thanks': typeof PosterThanksRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/go/dads': typeof GoDadsRoute
  '/go/thanks-dad': typeof GoThanksDadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/peptides': typeof PeptidesRoute
  '/poster': typeof PosterRoute
  '/poster-thanks': typeof PosterThanksRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/go/dads': typeof GoDadsRoute
  '/go/thanks-dad': typeof GoThanksDadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/peptides'
    | '/poster'
    | '/poster-thanks'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/go/dads'
    | '/go/thanks-dad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/peptides'
    | '/poster'
    | '/poster-thanks'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/go/dads'
    | '/go/thanks-dad'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/peptides'
    | '/poster'
    | '/poster-thanks'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/go/dads'
    | '/go/thanks-dad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PeptidesRoute: typeof PeptidesRoute
  PosterRoute: typeof PosterRoute
  PosterThanksRoute: typeof PosterThanksRoute
  PrivacyRoute: typeof PrivacyRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  GoDadsRoute: typeof GoDadsRoute
  GoThanksDadRoute: typeof GoThanksDadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster-thanks': {
      id: '/poster-thanks'
      path: '/poster-thanks'
      fullPath: '/poster-thanks'
      preLoaderRoute: typeof PosterThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster': {
      id: '/poster'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peptides': {
      id: '/peptides'
      path: '/peptides'
      fullPath: '/peptides'
      preLoaderRoute: typeof PeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/thanks-dad': {
      id: '/go/thanks-dad'
      path: '/go/thanks-dad'
      fullPath: '/go/thanks-dad'
      preLoaderRoute: typeof GoThanksDadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/dads': {
      id: '/go/dads'
      path: '/go/dads'
      fullPath: '/go/dads'
      preLoaderRoute: typeof GoDadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PeptidesRoute: PeptidesRoute,
  PosterRoute: PosterRoute,
  PosterThanksRoute: PosterThanksRoute,
  PrivacyRoute: PrivacyRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  GoDadsRoute: GoDadsRoute,
  GoThanksDadRoute: GoThanksDadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
