/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PeptidesRouteImport } from './routes/peptides'
import { Route as PosterRouteImport } from './routes/poster'
import { Route as PosterThanksRouteImport } from './routes/poster-thanks'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountActivateRouteImport } from './routes/account/activate'
import { Route as AccountRecoverRouteImport } from './routes/account/recover'
import { Route as AccountSignInRouteImport } from './routes/account/sign-in'
import { Route as AccountSignOutRouteImport } from './routes/account/sign-out'
import { Route as AccountVerifyRouteImport } from './routes/account/verify'
import { Route as GoDadsRouteImport } from './routes/go/dads'
import { Route as GoThanksDadRouteImport } from './routes/go/thanks-dad'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalRightsRouteImport } from './routes/portal.rights'
import { Route as StaffSignInRouteImport } from './routes/staff.sign-in'
import { Route as ApiJourneyIntentRouteImport } from './routes/api/journey/intent'
import { Route as ApiMeasurementConsentRouteImport } from './routes/api/measurement/consent'
import { Route as ApiMeasurementEventsRouteImport } from './routes/api/measurement/events'
import { Route as ApiPaymentsCheckoutRouteImport } from './routes/api/payments/checkout'
import { Route as ApiPaymentsStripeWebhookRouteImport } from './routes/api/payments/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PeptidesRoute = PeptidesRouteImport.update({
  id: '/peptides',
  path: '/peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterRoute = PosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterThanksRoute = PosterThanksRouteImport.update({
  id: '/poster-thanks',
  path: '/poster-thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountActivateRoute = AccountActivateRouteImport.update({
  id: '/account/activate',
  path: '/account/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRecoverRoute = AccountRecoverRouteImport.update({
  id: '/account/recover',
  path: '/account/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignInRoute = AccountSignInRouteImport.update({
  id: '/account/sign-in',
  path: '/account/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignOutRoute = AccountSignOutRouteImport.update({
  id: '/account/sign-out',
  path: '/account/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyRoute = AccountVerifyRouteImport.update({
  id: '/account/verify',
  path: '/account/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const GoDadsRoute = GoDadsRouteImport.update({
  id: '/go/dads',
  path: '/go/dads',
  getParentRoute: () => rootRouteImport,
} as any)
const GoThanksDadRoute = GoThanksDadRouteImport.update({
  id: '/go/thanks-dad',
  path: '/go/thanks-dad',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRightsRoute = PortalRightsRouteImport.update({
  id: '/portal/rights',
  path: '/portal/rights',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignInRoute = StaffSignInRouteImport.update({
  id: '/staff/sign-in',
  path: '/staff/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJourneyIntentRoute = ApiJourneyIntentRouteImport.update({
  id: '/api/journey/intent',
  path: '/api/journey/intent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeasurementConsentRoute = ApiMeasurementConsentRouteImport.update({
  id: '/api/measurement/consent',
  path: '/api/measurement/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeasurementEventsRoute = ApiMeasurementEventsRouteImport.update({
  id: '/api/measurement/events',
  path: '/api/measurement/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCheckoutRoute = ApiPaymentsCheckoutRouteImport.update({
  id: '/api/payments/checkout',
  path: '/api/payments/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsStripeWebhookRoute =
  ApiPaymentsStripeWebhookRouteImport.update({
    id: '/api/payments/stripe/webhook',
    path: '/api/payments/stripe/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/peptides': typeof PeptidesRoute
  '/poster': typeof PosterRoute
  '/poster-thanks': typeof PosterThanksRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/account/activate': typeof AccountActivateRoute
  '/account/recover': typeof AccountRecoverRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/account/sign-out': typeof AccountSignOutRoute
  '/account/verify': typeof AccountVerifyRoute
  '/go/dads': typeof GoDadsRoute
  '/go/thanks-dad': typeof GoThanksDadRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/rights': typeof PortalRightsRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/portal/': typeof PortalIndexRoute
  '/api/journey/intent': typeof ApiJourneyIntentRoute
  '/api/measurement/consent': typeof ApiMeasurementConsentRoute
  '/api/measurement/events': typeof ApiMeasurementEventsRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/stripe/webhook': typeof ApiPaymentsStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/peptides': typeof PeptidesRoute
  '/poster': typeof PosterRoute
  '/poster-thanks': typeof PosterThanksRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/account/activate': typeof AccountActivateRoute
  '/account/recover': typeof AccountRecoverRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/account/sign-out': typeof AccountSignOutRoute
  '/account/verify': typeof AccountVerifyRoute
  '/go/dads': typeof GoDadsRoute
  '/go/thanks-dad': typeof GoThanksDadRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/rights': typeof PortalRightsRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/portal': typeof PortalIndexRoute
  '/api/journey/intent': typeof ApiJourneyIntentRoute
  '/api/measurement/consent': typeof ApiMeasurementConsentRoute
  '/api/measurement/events': typeof ApiMeasurementEventsRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/stripe/webhook': typeof ApiPaymentsStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/peptides': typeof PeptidesRoute
  '/poster': typeof PosterRoute
  '/poster-thanks': typeof PosterThanksRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/account/activate': typeof AccountActivateRoute
  '/account/recover': typeof AccountRecoverRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/account/sign-out': typeof AccountSignOutRoute
  '/account/verify': typeof AccountVerifyRoute
  '/go/dads': typeof GoDadsRoute
  '/go/thanks-dad': typeof GoThanksDadRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/rights': typeof PortalRightsRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/portal/': typeof PortalIndexRoute
  '/api/journey/intent': typeof ApiJourneyIntentRoute
  '/api/measurement/consent': typeof ApiMeasurementConsentRoute
  '/api/measurement/events': typeof ApiMeasurementEventsRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/stripe/webhook': typeof ApiPaymentsStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/peptides'
    | '/poster'
    | '/poster-thanks'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/account/activate'
    | '/account/recover'
    | '/account/sign-in'
    | '/account/sign-out'
    | '/account/verify'
    | '/go/dads'
    | '/go/thanks-dad'
    | '/portal/profile'
    | '/portal/rights'
    | '/staff/sign-in'
    | '/portal/'
    | '/api/journey/intent'
    | '/api/measurement/consent'
    | '/api/measurement/events'
    | '/api/payments/checkout'
    | '/api/payments/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/peptides'
    | '/poster'
    | '/poster-thanks'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/account/activate'
    | '/account/recover'
    | '/account/sign-in'
    | '/account/sign-out'
    | '/account/verify'
    | '/go/dads'
    | '/go/thanks-dad'
    | '/portal/profile'
    | '/portal/rights'
    | '/staff/sign-in'
    | '/portal'
    | '/api/journey/intent'
    | '/api/measurement/consent'
    | '/api/measurement/events'
    | '/api/payments/checkout'
    | '/api/payments/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/peptides'
    | '/poster'
    | '/poster-thanks'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/account/activate'
    | '/account/recover'
    | '/account/sign-in'
    | '/account/sign-out'
    | '/account/verify'
    | '/go/dads'
    | '/go/thanks-dad'
    | '/portal/profile'
    | '/portal/rights'
    | '/staff/sign-in'
    | '/portal/'
    | '/api/journey/intent'
    | '/api/measurement/consent'
    | '/api/measurement/events'
    | '/api/payments/checkout'
    | '/api/payments/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PeptidesRoute: typeof PeptidesRoute
  PosterRoute: typeof PosterRoute
  PosterThanksRoute: typeof PosterThanksRoute
  PrivacyRoute: typeof PrivacyRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  AccountActivateRoute: typeof AccountActivateRoute
  AccountRecoverRoute: typeof AccountRecoverRoute
  AccountSignInRoute: typeof AccountSignInRoute
  AccountSignOutRoute: typeof AccountSignOutRoute
  AccountVerifyRoute: typeof AccountVerifyRoute
  GoDadsRoute: typeof GoDadsRoute
  GoThanksDadRoute: typeof GoThanksDadRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRightsRoute: typeof PortalRightsRoute
  StaffSignInRoute: typeof StaffSignInRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ApiJourneyIntentRoute: typeof ApiJourneyIntentRoute
  ApiMeasurementConsentRoute: typeof ApiMeasurementConsentRoute
  ApiMeasurementEventsRoute: typeof ApiMeasurementEventsRoute
  ApiPaymentsCheckoutRoute: typeof ApiPaymentsCheckoutRoute
  ApiPaymentsStripeWebhookRoute: typeof ApiPaymentsStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peptides': {
      id: '/peptides'
      path: '/peptides'
      fullPath: '/peptides'
      preLoaderRoute: typeof PeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster': {
      id: '/poster'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster-thanks': {
      id: '/poster-thanks'
      path: '/poster-thanks'
      fullPath: '/poster-thanks'
      preLoaderRoute: typeof PosterThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/activate': {
      id: '/account/activate'
      path: '/account/activate'
      fullPath: '/account/activate'
      preLoaderRoute: typeof AccountActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/recover': {
      id: '/account/recover'
      path: '/account/recover'
      fullPath: '/account/recover'
      preLoaderRoute: typeof AccountRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/sign-in': {
      id: '/account/sign-in'
      path: '/account/sign-in'
      fullPath: '/account/sign-in'
      preLoaderRoute: typeof AccountSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/sign-out': {
      id: '/account/sign-out'
      path: '/account/sign-out'
      fullPath: '/account/sign-out'
      preLoaderRoute: typeof AccountSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify': {
      id: '/account/verify'
      path: '/account/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AccountVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/dads': {
      id: '/go/dads'
      path: '/go/dads'
      fullPath: '/go/dads'
      preLoaderRoute: typeof GoDadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/thanks-dad': {
      id: '/go/thanks-dad'
      path: '/go/thanks-dad'
      fullPath: '/go/thanks-dad'
      preLoaderRoute: typeof GoThanksDadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/rights': {
      id: '/portal/rights'
      path: '/portal/rights'
      fullPath: '/portal/rights'
      preLoaderRoute: typeof PortalRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/sign-in': {
      id: '/staff/sign-in'
      path: '/staff/sign-in'
      fullPath: '/staff/sign-in'
      preLoaderRoute: typeof StaffSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journey/intent': {
      id: '/api/journey/intent'
      path: '/api/journey/intent'
      fullPath: '/api/journey/intent'
      preLoaderRoute: typeof ApiJourneyIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/measurement/consent': {
      id: '/api/measurement/consent'
      path: '/api/measurement/consent'
      fullPath: '/api/measurement/consent'
      preLoaderRoute: typeof ApiMeasurementConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/measurement/events': {
      id: '/api/measurement/events'
      path: '/api/measurement/events'
      fullPath: '/api/measurement/events'
      preLoaderRoute: typeof ApiMeasurementEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/checkout': {
      id: '/api/payments/checkout'
      path: '/api/payments/checkout'
      fullPath: '/api/payments/checkout'
      preLoaderRoute: typeof ApiPaymentsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/stripe/webhook': {
      id: '/api/payments/stripe/webhook'
      path: '/api/payments/stripe/webhook'
      fullPath: '/api/payments/stripe/webhook'
      preLoaderRoute: typeof ApiPaymentsStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PeptidesRoute: PeptidesRoute,
  PosterRoute: PosterRoute,
  PosterThanksRoute: PosterThanksRoute,
  PrivacyRoute: PrivacyRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  AccountActivateRoute: AccountActivateRoute,
  AccountRecoverRoute: AccountRecoverRoute,
  AccountSignInRoute: AccountSignInRoute,
  AccountSignOutRoute: AccountSignOutRoute,
  AccountVerifyRoute: AccountVerifyRoute,
  GoDadsRoute: GoDadsRoute,
  GoThanksDadRoute: GoThanksDadRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRightsRoute: PortalRightsRoute,
  StaffSignInRoute: StaffSignInRoute,
  PortalIndexRoute: PortalIndexRoute,
  ApiJourneyIntentRoute: ApiJourneyIntentRoute,
  ApiMeasurementConsentRoute: ApiMeasurementConsentRoute,
  ApiMeasurementEventsRoute: ApiMeasurementEventsRoute,
  ApiPaymentsCheckoutRoute: ApiPaymentsCheckoutRoute,
  ApiPaymentsStripeWebhookRoute: ApiPaymentsStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
